### ISSUE TITLE
Could not load library libcublasLt.so.12.

### ISSUE THREAD

**Issue by TheNetStriker** [bugsyb/recognize_docker#2]
I've just tested your container image, but I get the following error when trying to run recognize with GPU acceleration:

```
{
   "reqId":"YhPskH0byNEBPwuVNS59",
   "level":2,
   "time":"2023-02-19T17:50:14+00:00",
   "remoteAddr":"",
   "user":"--",
   "app":"recognize",
   "method":"",
   "url":"--",
   "message":"Classifier process output: 2023-02-19 17:50:04.773140: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n2023-02-19 17:50:04.848781: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n2023-02-19 17:50:04.849224: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n2023-02-19 17:50:06.242900: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n2023-02-19 17:50:06.243328: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n2023-02-19 17:50:06.243622: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n2023-02-19 17:50:06.243954: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3376 MB memory:  -> device: 0, name: Quadro M2000, pci bus id: 0000:00:10.0, compute capability: 5.2\nCould not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory\n",
   "userAgent":"--",
   "version":"25.0.3.2",
   "data":{
      "app":"recognize"
   }
}
```

For some reason the application is looking for libcublasLt.so version 12 instead of 11.

Any ideas why this is happening?

**Comment by bugsyb** [comment]
Is there a chance that your Dockerfile has been amended?
I just tested it at my end  on separate docker host, pulled from git and built the image and this is what I'm seeing:
```
# docker run --rm -it local/nextcloud-recognize-gpu:latest-test /bin/bash
root@4390a28398dd:/var/www/html# find / -iname libcublasLt*
/usr/local/lib/python3.9/dist-packages/nvidia/cublas/lib/libcublasLt.so.11
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcublasLt.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libcublasLt.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcublasLt.so.11.11.3.6
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcublasLt.so.11
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcublasLt_static.a
```

**Comment by bugsyb** [comment]
Built it documented way:
```
DOCKER_BUILDKIT=1 docker build -t local/nextcloud-recognize-gpu:latest-test .
```

**Comment by TheNetStriker** [comment]
I also found the libcublasLt.so.11 in the filesystem, but for some reason the Recognize app also needs the libcublasLt.so.12 file. I've now simply added the "libcublas-12-0" on the two lines behind the libcudnn8-dev for the apt installation and now it works.

This is now the output of your search in my container:

find / -iname libcublasLt*
/usr/local/lib/python3.9/dist-packages/nvidia/cublas/lib/libcublasLt.so.11
/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libcublasLt.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcublasLt.so.11
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcublasLt.so.11.11.3.6
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcublasLt_static.a
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcublasLt.so
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcublasLt.so.12.0.2.224
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcublasLt.so.12

Any idea why this requires one library from the Cuda SDK 12?

**Comment by bugsyb** [comment]
My suspicion is that tensorflow/recognize asks for version 12 whilst indeed it builds with version 11 (which wasn't the case at the time when I've built the image).
My bad, it is not locked to specific releases.

Not sure why tensorflow/recognize would be forcing version 12.

Other option is to try to force install of version 12. 
I don't have time for next days to play with it, though if you'd suggest how to lock on versions either way, I'm happy to apply mods to the Dockerfile.

**Comment by bugsyb** [comment]
Seems like we've been writing at the same time, as I did first misread your commend and deleted wrong replies.

Answering to question - not sure why Cuda SDK 12 would be required by recognize, @marcelklehr would be better placed to answer this question.

**Comment by bugsyb** [comment]
Ok, quick look at `Dockerfile` shows that I've prepped it already for similar situation.
Building at my end right now with:
`
ENV CUDA_VERSION=12.0
ENV CUDA_VERSION_NVIDIA=12-0
`
On the test build host, I don't have GPU though will be able to test if build works fine at least.
If you've time to check that mod at your end, that would be grant.

**Comment by TheNetStriker** [comment]
I've just tested that, but now I get the following error:

Classifier process output: 2023-02-25 12:54:52.440329: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /0_nondist/conda//lib/:

**Comment by bugsyb** [comment]
I'm sorry, I don't have spare time to focus on it - did put it away earlier as wanted to come back with a solution and couldn't find time during last weeks. 
Issue might have something to do with paths (LD_LIBRARY_PATH). Have a look if you've libcudart.so* somewhere and what are the files. Once I can focus back on it I'll work on getting fully working solution again (have work/private related stuff going on which gets the prio at the moment).

**Comment by bugsyb** [comment]
Apologies for huge delay, didn't have time due to professional & private overload.

Build process has been added to accustom changes in library dependencies - not sure if and why wouldn't it load correctly at your end. Whilst fixing this and making sure it all goes well for current ones - I've noticed somewhere v12 started to pop in.

To avoid these issues, more control over versions has been added (https://github.com/bugsyb/recognize_docker/commit/c774ec1ba79fb64bef84a887a5b9a7408562cfcb) and most importantly new nVIDIA TensorFlow image based option (https://github.com/bugsyb/recognize_docker/tree/main/nvidia-tensor-based)  has been added with flexibility to chose version of Nextcloud and fpm/apache frontend. 
Have a look at it and if it wouldn't build still - let me know.

Fixed by:
https://github.com/bugsyb/recognize_docker/commit/903ef3d0e162cd258f0e627fd4696eb0085958eb

**Comment by bugsyb** [comment]
The above problem could be also due to wrong PHP version combination selection. 
For other reasons, I've been playing with versions and did run into situation that `libcudart.so.11.0` wasn't included at all.
Reasoning behind was, that php/8.4 version was forced, whilst Nextcloud by default is based on php/8.2 image, and as such uses such tag in the build process. Whilst version 8.4 was built, it wasn't used, and as php is built on top of the tensorflow image, later tagged as what the build is based on (Debian/bookworm-slim) - it all made it skipping the right image and effectively skipping the Cuda based image all together.

Previous version, at the time of your testing, had proper defaults, same as current has - it should all work, though thought would share findings.
This is the today commit https://github.com/bugsyb/recognize_docker/commit/0dbb939d3326f9d36a7d648906d6e7ae3348b4ae

Easiest to use is https://github.com/bugsyb/recognize_docker/tree/main/nvidia-tensor-based image. This one is the one I used at the moment. There were thoughts about trimming it down, though majority of the size is taken by CUDA and related as well as Recognize image with all. In total after current build it is ~19GB image and works.
